"""revert_to_local_auth

Revision ID: 988a7b6a9a0c
Revises: d010c9c8ac1c
Create Date: 2026-06-30 15:02:15.342285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988a7b6a9a0c'
down_revision = 'd010c9c8ac1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
